# EXAMPLE GAME CONFIGURATION FILE.
# PLEASE REVIEW AND MODIFY IF YOU WISH TO RUN YOUR OWN SERVERS!
# Some arguments are provided as absolute paths and only work on my machine.

[server_assignment]
players.maximum = 4096
players.preferred = 666
instances.count = 1

[game_setup]
# Aliases for "v348" is "2018M", "v463" is "2021E".
roblox_version = '2021'

title = 'òó'
description = ''
creator.name = 'ÒÓ'
startup_script = ''

[game_setup.place]
path = 'd:\Users\username\Documents\Leaked-Roblox-Places-main\RBXL\BETA___T_C__City_of_Istanbul.rbxl'
# When game:SavePlace() is called, overwirtes the place at `.path`
enable_saveplace = false

[game_setup.database]
path = '_.sqlite'
clear_on_start = false

[game_setup.icon]
# Stretches to 16:9.
path = 'c:\Users\USERNAME\Pictures\Byfron Icon.png'


[server_core]
retrieve_default_user_code = '''
function(tick) -- float -> str
    return string.format('Tick %d', tick)
end
'''

check_user_allowed = '''
function(user_code) -- string -> bool
    return true
end
'''

retrieve_avatar_type = '''
function(user_code) -- str -> str
    return 'R15'
end
'''

retrieve_avatar_items = '''
function(user_code) -- str -> [str]
    return {
        301820642,
        5243961918,
        11857928130,
        86487700,
        16630147,
    }
end
'''

retrieve_avatar_colors = '''
function(user_code) -- str -> {[str]: number}
    return {
        head = 1013,
        left_arm = 1013,
        left_leg = 1013,
        right_arm = 1013,
        right_leg = 1013,
        torso = 1013,
    }
end
'''

retrieve_avatar_scales = '''
function(user_code) -- str -> {[str]: number}
    return {
        height = 1,
        width = 0.8,
        head = 1,
        depth = 0.8,
        proportion = 0,
        body_type = 0,
    }
end
'''

retrieve_username = '''
function(user_code) -- str -> str
    return user_code
end
'''

retrieve_user_id = '''
function(user_code) -- str -> int
    return math.random(1, 16777216)
end
'''

retrieve_account_age = '''
function(user_code) -- str -> int
    return 6969
end
'''

filter_text = '''
function(user_code, text)
    return text:gsub('oo','òó'):gsub('OO','ÒÓ'):gsub('ee','èé'):gsub('EE','ÈÉ'):gsub('Roblox','Rōblox'):gsub('ROBLOX','RŌBLOX')
end
'''

chat_style = 'ClassicAndBubble'
