# EXAMPLE GAME CONFIGURATION FILE.
# PLEASE REVIEW AND MODIFY IF YOU WISH TO RUN YOUR OWN SERVERS!

[server_assignment]
players.maximum = 4096
players.preferred = 666
instances.count = 1

[game_setup]
# Aliases for "v348" is "2018M", "v463" is "2021E", etc.
# roblox_version = '2021E'
roblox_version = '2018M'
place_path = 'c:\Users\USERNAME\Documents\Roblox Files\Roblox Hacked Place Database 2 - MrManchot\Build and Race.rbxl'
icon_path = 'C:\Users\USERNAME\Pictures\097050bd37142a4080975bb8e415d2b8.jpg'
name = '666'
description = ''
creator.name = 'ÒÓ'


[server_core]
chat_style = 'ClassicAndBubble'
avatar_type = 'R6'

# Python function `RESULT` which generates an RFD-specific user code if one isn't provided.
# Server maintainers should review the code because it's used by 'eval'.
retrieve_default_user_code = '''
def RESULT(tick: float) -> str:
    return f'Tick {tick}'
'''

# Python function `RESULT` which evaluates the player's `Name` value from their RFD-specific user code.
# Server maintainers should review the code because it's used by 'eval'.
retrieve_username = '''
def RESULT(user_code: str) -> str:
    return user_code
'''

# Python function `RESULT` which evaluates the player's `UserId` value from their RFD-specific user code.
# Server maintainers should review the code because it's used by 'eval'.
retrieve_user_id = '''
def RESULT(user_code: str) -> int:
    return hash(user_code)%1024
'''

# Python function `RESULT` which evaluates the player's `AccountAge` value from their RFD-specific user code.
# Server maintainers should review the code because it's used by 'eval'.
retrieve_account_age = '''
def RESULT(user_code: str) -> int:
    return 6969
'''

# Python function `RESULT` which filters text.
# Server maintainers should review the code because it's used by 'eval'.
filter_text = '''
def RESULT(user_code: str, text: str) -> str:
    return text
      .replace('oo','òó')
      .replace('OO','ÒÓ')
'''
